<a href="https://colab.research.google.com/github/Nehag-29/practice1/blob/main/ass_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
array_1d=np.array([10,20,30,40,40])
added_array=array_1d+2
mul_array=array_1d*3
div_array=array_1d / 2
print(added_array)
print(mul_array)
print(div_array)

[12 22 32 42 42]
[ 30  60  90 120 120]
[ 5. 10. 15. 20. 20.]


In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
rev_array=np.flip(arr)
print(rev_array)
x = np.array([1,2,3,4,5,1,2,1,1,1])

[5 4 6 3 2 1]


In [4]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
def most_frequent_value_and_indices(arr):
  values,counts=np.unique(arr,return_counts=True)
  most_frequent_value=values[np.argmax(counts)]
  indices=np.where(arr==most_frequent_value)[0]
  return most_frequent_value,indices
x_value,x_indices=most_frequent_value_and_indices(x)
y_value,y_indices=most_frequent_value_and_indices(y)
print(x_value," ",x_indices)
print(y_value," ",y_indices)

1   [0 5 7 8 9]
1   [0 1 2]


In [3]:
 import numpy as np
 your_name=np.linspace(10,100,25)
 print("array",your_name)
 print("dimensions:",your_name.ndim)
 print("shape",your_name.shape)
 print("total elements",your_name.size)
 print("data type",your_name.dtype)
 print("total bytes",your_name.nbytes)
 transpose_reshape=your_name.reshape(-1,1)
 print("transpose using reshape:",transpose_reshape)
 transpose_T=your_name.T
 print("\nTranspose using T attribute:", transpose_T)

array [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions: 1
shape (25,)
total elements 25
data type float64
total bytes 200
transpose using reshape: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [4]:
import numpy as np
ucs420_yourname=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
mean_value=np.mean(ucs420_yourname)
median_value=np.median(ucs420_yourname)
max_value=np.max(ucs420_yourname)
min_value=np.min(ucs420_yourname)
unique_elements=np.unique(ucs420_yourname)
print("Mean:",mean_value)
print("Median:",median_value)
print("Max value",max_value)
print("min_value",min_value)
print("unique elements",unique_elements)
reshape_ucs420_yourname=ucs420_yourname.reshape(4,3)
print("reshaped array:",reshape_ucs420_yourname)
resized_ucs420_yourname=np.resize(ucs420_yourname,(2,3))
print("resized array is:",resized_ucs420_yourname)

Mean: 43.333333333333336
Median: 37.5
Max value 90
min_value 10
unique elements [10 15 20 30 35 40 50 60 70 80 90]
reshaped array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resized array is: [[10 20 30]
 [40 50 60]]
